import uuid

from sqlalchemy.orm import Session

from app.models.fridge import FridgeItem, UserFridge
from app.models.ingredient import Ingredient
from app.models.profile import UserPreference, UserProfile, UserSetting
from app.models.recipe import (
    CookedRecipe,
    CookedRecipePhoto,
    Recipe,
    RecipeIngredient,
    SavedRecipe,
)
from app.models.user import User
from app.services.auth import hash_password

SAMPLE_USER_ID = uuid.UUID("11111111-1111-1111-1111-111111111111")
ADMIN_USER_ID = uuid.UUID("00000000-0000-0000-0000-000000000001")


def seed_sample_data(db: Session) -> None:
    # admin 테스트 계정
    existing_admin = db.query(User).filter(User.id == ADMIN_USER_ID).first()
    if not existing_admin:
        admin = User(
            id=ADMIN_USER_ID,
            email="admin@babsim.com",
            nickname="admin",
            cooking_level="intermediate",
            auth_provider="local",
            password_hash=hash_password("admin"),
        )
        db.add(admin)
        db.flush()
        db.add(
            UserProfile(
                user_id=ADMIN_USER_ID,
                display_name="admin",
                email="admin@babsim.com",
            )
        )
        db.add(
            UserSetting(
                user_id=ADMIN_USER_ID,
                expiration_alerts=True,
                recipe_suggestions=True,
                measurement_units="Metric",
                language="Korean",
            )
        )
        db.add(
            UserPreference(
                user_id=ADMIN_USER_ID,
            )
        )
        db.commit()

    existing_user = db.query(User).filter(User.id == SAMPLE_USER_ID).first()
    if existing_user:
        return

    user = User(
        id=SAMPLE_USER_ID,
        email="alex.user@example.com",
        nickname="Alex User",
        cooking_level="intermediate",
        auth_provider="local",
        password_hash=hash_password("password123"),
    )
    db.add(user)
    db.flush()
    db.add(
        UserProfile(
            user_id=SAMPLE_USER_ID,
            display_name="Alex User",
            title="Master Chef in Training",
            email="alex.user@example.com",
            phone="+1 (555) 123-4567",
            avatar_url=None,
        )
    )
    db.add(
        UserSetting(
            user_id=SAMPLE_USER_ID,
            expiration_alerts=True,
            recipe_suggestions=True,
            measurement_units="Metric",
            language="Korean",
        )
    )

    for kind, values in {
        "allergy": ["Peanuts", "Shellfish"],
        "disliked": ["Eggplant", "Cucumber"],
        "tool": ["Air Fryer", "Blender"],
    }.items():
        for value in values:
            db.add(UserPreference(user_id=SAMPLE_USER_ID, kind=kind, value=value))

    # 재료 목록 (name_ko, name_en, category)
    ingredient_rows = [
        # 곡물
        ("멥쌀", "non-glutinous rice", "곡물"),
        ("찹쌀", "glutinous rice", "곡물"),
        ("소면", "thin wheat noodles", "곡물"),
        ("우동면", "udon noodles", "곡물"),
        ("냉면용 메밀면", "cold buckwheat noodles", "곡물"),
        ("라면 면발", "ramen noodles", "곡물"),
        ("스파게티면", "spaghetti noodles", "곡물"),
        ("밥", "cooked rice", "곡물"),
        ("떡볶이 떡", "rice cakes", "곡물"),
        ("밀가루", "flour", "곡물"),
        ("찹쌀가루", "glutinous rice flour", "곡물"),
        ("당면", "glass noodles", "곡물"),
        # 육류
        ("소갈비", "beef short ribs", "육류"),
        ("다진 소고기", "minced beef", "육류"),
        ("소고기(양지머리)", "beef brisket", "육류"),
        ("소고기(등심)", "beef sirloin", "육류"),
        ("국거리용 소고기", "stew beef", "육류"),
        ("돼지고기(삼겹살)", "pork belly", "육류"),
        ("돼지고기(목살)", "pork neck", "육류"),
        ("돼지고기(다짐육)", "ground pork", "육류"),
        ("돼지 등뼈", "pork spine", "육류"),
        ("닭다리 살", "chicken thigh meat", "육류"),
        ("닭", "whole chicken", "육류"),
        ("오리 고기", "duck meat", "육류"),
        ("베이컨", "bacon", "육류"),
        ("소시지", "sausage", "육류"),
        ("스팸", "Spam", "육류"),
        # 해산물
        ("오징어", "squid", "해산물"),
        ("참치(캔)", "canned tuna", "해산물"),
        ("어묵", "fish cake", "해산물"),
        ("잔멸치볶음", "stir-fried dried anchovies", "해산물"),
        ("국물용 멸치", "dried anchovies for broth", "해산물"),
        # 채소
        ("팥", "red beans", "채소"),
        ("검은콩", "black beans", "채소"),
        ("수수", "sorghum", "채소"),
        ("차조", "millet", "채소"),
        ("콩나물", "bean sprouts", "채소"),
        ("숙주", "soybean sprouts", "채소"),
        ("시금치", "spinach", "채소"),
        ("양배추", "cabbage", "채소"),
        ("양파", "onion", "채소"),
        ("대파", "green onion", "채소"),
        ("쪽파", "green onion (thin)", "채소"),
        ("실파", "thin green onion", "채소"),
        ("청양고추", "cheongyang chili pepper", "채소"),
        ("홍고추", "red chili pepper", "채소"),
        ("풋고추", "green chili pepper", "채소"),
        ("당근", "carrot", "채소"),
        ("감자", "potato", "채소"),
        ("고구마", "sweet potato", "채소"),
        ("무", "radish", "채소"),
        ("애호박", "zucchini", "채소"),
        ("마늘", "garlic", "채소"),
        ("생강", "ginger", "채소"),
        ("토마토", "tomato", "채소"),
        ("느타리버섯", "oyster mushrooms", "채소"),
        ("표고버섯", "shiitake mushrooms", "채소"),
        ("마른 표고버섯", "dried shiitake mushrooms", "채소"),
        ("새송이버섯", "king oyster mushroom", "채소"),
        ("피망", "bell pepper", "채소"),
        ("파프리카", "paprika", "채소"),
        ("깻잎", "perilla leaves", "채소"),
        ("부추", "garlic chives", "채소"),
        ("우엉", "burdock root", "채소"),
        ("배추김치", "napa kimchi", "채소"),
        ("묵은지", "aged kimchi", "채소"),
        ("시래기", "dried radish greens", "채소"),
        ("단무지", "pickled radish", "채소"),
        ("오이", "cucumber", "채소"),
        ("상추", "lettuce", "채소"),
        ("아보카도", "avocado", "채소"),
        ("배", "pear", "과일"),
        ("사과", "apple", "과일"),
        ("과일(블루베리 등)", "fruit (blueberries etc)", "과일"),
        ("밤", "chestnuts", "과일"),
        ("대추", "jujube", "과일"),
        # 유제품/계란
        ("계란", "egg", "유제품/계란"),
        ("우유", "milk", "유제품/계란"),
        ("생크림", "heavy cream", "유제품/계란"),
        ("슬라이스치즈", "slice cheese", "유제품/계란"),
        ("파마산 치즈", "parmesan cheese", "유제품/계란"),
        ("그릭요거트", "Greek yogurt", "유제품/계란"),
        # 두부/콩류
        ("두부", "tofu", "두부/콩류"),
        ("순두부", "soft tofu", "두부/콩류"),
        # 양념/소스
        ("된장", "doenjang (soybean paste)", "양념"),
        ("고추장", "gochujang", "양념"),
        ("간장", "soy sauce", "양념"),
        ("국간장", "soup soy sauce", "양념"),
        ("진간장", "dark soy sauce", "양념"),
        ("고춧가루", "chili powder", "양념"),
        ("참기름", "sesame oil", "양념"),
        ("들기름", "perilla oil", "양념"),
        ("식용유", "cooking oil", "양념"),
        ("올리브유", "olive oil", "양념"),
        ("설탕", "sugar", "양념"),
        ("물엿", "corn syrup", "양념"),
        ("올리고당", "oligosaccharide syrup", "양념"),
        ("알룰로스", "allulose", "양념"),
        ("식초", "vinegar", "양념"),
        ("소금", "salt", "양념"),
        ("후춧가루", "pepper", "양념"),
        ("깨", "sesame seeds", "양념"),
        ("깨소금", "sesame salt", "양념"),
        ("청주", "cheongju", "양념"),
        ("쯔유", "tsuyu sauce", "양념"),
        ("굴소스", "oyster sauce", "양념"),
        ("마요네즈", "mayonnaise", "양념"),
        ("케찹", "ketchup", "양념"),
        ("스리라차", "sriracha", "양념"),
        ("머스타드", "mustard", "양념"),
        ("카레가루", "curry powder", "양념"),
        ("토마토퓨레", "tomato puree", "양념"),
        ("스파게티 소스", "spaghetti sauce", "양념"),
        ("월계수잎", "bay leaves", "양념"),
        ("페페론치노", "peperoncino", "양념"),
        ("와사비", "wasabi", "양념"),
        ("트러플오일", "truffle oil", "양념"),
        ("들깨 가루", "perilla seed powder", "양념"),
        ("잣가루", "pine nut powder", "양념"),
        ("녹말가루", "cornstarch", "양념"),
        ("코인육수", "broth cube", "양념"),
        # 기타
        ("또띠아", "tortilla", "기타"),
        ("그레놀라", "granola", "기타"),
        ("꿀", "honey", "기타"),
        ("유부", "inari (fried tofu pouch)", "기타"),
        ("구운 김", "roasted seaweed", "기타"),
        ("김가루", "shredded seaweed", "기타"),
        ("마른 미역", "dried seaweed (miyeok)", "기타"),
        ("시판 초밥 소스", "store-bought sushi seasoning", "기타"),
        ("시즈닝가루", "seasoning powder", "기타"),
        ("파슬리", "parsley", "기타"),
        ("딜", "dill", "기타"),
    ]

    ingredients = {}
    for name_ko, name_en, category in ingredient_rows:
        ingredient = Ingredient(name_ko=name_ko, name_en=name_en, category=category)
        db.add(ingredient)
        db.flush()
        ingredients[name_ko] = ingredient

    # 냉장고 (샘플용)
    fridge_rows = [
        ("Main Fridge", "main", True),
        ("Kimchi Fridge", "kimchi", False),
    ]
    fridges = {}
    for name, kind, is_primary in fridge_rows:
        fridge = UserFridge(
            user_id=SAMPLE_USER_ID,
            name=name,
            kind=kind,
            is_primary=is_primary,
        )
        db.add(fridge)
        db.flush()
        fridges[name] = fridge

    fridge_items = [
        ("Main Fridge", "계란", "6개", "refrigerated", 7, True),
        ("Main Fridge", "두부", "1모", "refrigerated", 5, True),
        ("Main Fridge", "간장", "충분히", "room_temp", None, False),
        ("Main Fridge", "고추장", "충분히", "room_temp", None, False),
        ("Main Fridge", "된장", "충분히", "room_temp", None, False),
        ("Main Fridge", "대파", "1대", "refrigerated", 7, True),
        ("Main Fridge", "마늘", "한 줌", "refrigerated", 14, False),
        ("Kimchi Fridge", "배추김치", "2kg", "refrigerated", 30, True),
    ]
    for fridge_name, ingredient_name, quantity, storage_type, days, reminder in fridge_items:
        db.add(
            FridgeItem(
                user_id=SAMPLE_USER_ID,
                fridge_id=fridges[fridge_name].id,
                ingredient_id=ingredients[ingredient_name].id,
                quantity=quantity,
                storage_type=storage_type,
                days_until_expiry=days,
                expiry_reminder=reminder,
            )
        )

    # 레시피 데이터 (구글 시트 기반)
    recipe_rows = [
        {
            "id": 1,
            "title": "오곡밥",
            "slug": "ogokbap",
            "category": "Korean",
            "description": "멥쌀, 찹쌀, 팥, 검은콩, 수수, 차조를 넣어 지은 영양 가득한 밥.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "lunch",
            "dietary_tags": ["Vegan", "Gluten-Free"],
            "rating": 4.5,
            "cooking_time_minutes": 60,
            "serving_size": 4,
            "instructions": "준비하기\n1. 멥쌀과 찹쌀은 밥 짓기 30분 전에 씻어 물에 불렸다가 건진다.\n2. 팥은 깨끗이 씻어 냄비에 담고 충분히 잠길 정도로 물 2컵을 부어 불에 올린다. 끓어오르면 물은 따라 버리고, 다시 3컵 정도의 물을 부어 팥알이 터지지 않을 정도로 삶는다. 삶은 팥은 건지고 팥물은 따로 받아둔다.\n3. 콩은 씻어서 물에 2시간 동안 불렸다 건진다.\n4. 수수도 씻어서 물에 2시간 불리는 동안 여러 번 물을 갈아준다. 차조는 씻어서 건진다.\n조리하기\n1. 멥쌀과 찹쌀, 삶은 팥과 불린 콩, 수수를 합하여 냄비에 넣고 고루 섞는다.\n2. 팥 삶은 물 1컵과 물 1½컵을 합하여 총 2½컵을 계량한 다음 소금간을 하여 밥물을 만든다.\n3. 냄비에 밥물을 붓고 센 불에 올려 뚜껑을 닫고 끓인다.\n4. 밥이 끓어오르면 위에 차조를 얹고 중간 불로 줄여서 25분 동안 끓인다.\n5. 쌀알이 익어 퍼지면 불을 약하게 줄이고 5분간 뜸을 들인다.\n6. 주걱으로 위아래를 살살 섞어 그릇에 담는다.",
            "instructions_en": "Preparation:\n1. Wash non-glutinous and glutinous rice 30 minutes before cooking, soak in water, then drain.\n2. Wash red beans, add 2 cups of water to a pot, bring to a boil. Discard water, add 3 cups fresh water, simmer until beans are cooked but not bursting. Drain beans and reserve cooking water.\n3. Wash black beans, soak in water for 2 hours, drain.\n4. Wash sorghum, soak in water for 2 hours, changing water several times. Wash millet and drain.\nCooking:\n1. Combine both rices, cooked red beans, soaked black beans, and sorghum in a pot; mix well.\n2. Combine 1 cup red bean water + 1½ cups water = 2½ cups; season with salt.\n3. Pour over rice, cover, and bring to a boil over high heat.\n4. When boiling, add millet on top; reduce to medium heat, cook 25 minutes.\n5. When rice is cooked, reduce to low heat and let steam 5 minutes.\n6. Gently mix and serve.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("멥쌀", "2컵(450g)", False),
                ("찹쌀", "1컵(220g)", False),
                ("팥", "¼컵", False),
                ("검은콩", "½컵", False),
                ("수수", "½컵", False),
                ("차조", "¼컵", False),
                ("소금", "약간", True),
            ],
        },
        {
            "id": 2,
            "title": "된장찌개",
            "slug": "doenjang-jjigae",
            "category": "Korean",
            "description": "고기 기름에 된장을 볶아 깊은 맛을 낸 한국식 찌개.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "dinner",
            "dietary_tags": [],
            "rating": 4.7,
            "cooking_time_minutes": 20,
            "serving_size": 1,
            "instructions": "1. 냄비에다가 식용유에 고기 구워서 기름을 만든다.\n2. 중불로 줄여서, 된장이랑 고추장 (더 매운거 원하면 고추가루 반큰술)을 고기 기름에 같이 볶아준다.\n3. 물 붓고 나머지 재료를 한번에 다 넣고 한번 팔팔 끓여준다.",
            "instructions_en": "1. In a pot, cook the meat in cooking oil to render the fat.\n2. Reduce to medium heat; stir-fry doenjang and gochujang (add ½ tbsp chili powder for extra spice) in the meat drippings.\n3. Add water and all remaining ingredients at once; bring to a rolling boil.",
            "source": "박찬주",
            "image_url": None,
            "ingredients": [
                ("돼지고기(삼겹살)", "150g", False),
                ("양파", "½개", False),
                ("느타리버섯", "한 줌", True),
                ("두부", "¼모", False),
                ("대파", "¼쪽", False),
                ("청양고추", "1개", True),
                ("된장", "2큰술", False),
                ("고추장", "1큰술", False),
            ],
        },
        {
            "id": 3,
            "title": "김치볶음밥",
            "slug": "kimchi-bokkeumbap",
            "category": "Korean",
            "description": "김치와 밥을 함께 볶아 만드는 간단한 한 끼.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "lunch",
            "dietary_tags": ["Spicy"],
            "rating": 4.6,
            "cooking_time_minutes": 15,
            "serving_size": 2,
            "instructions": "1. 팬에 식용유를 두르고 김치를 볶는다.\n2. 밥을 넣고 함께 볶는다.\n3. 간장, 참기름으로 간을 맞추고 그릇에 담는다.",
            "instructions_en": "1. Heat oil in pan; stir-fry kimchi.\n2. Add rice; stir-fry together.\n3. Season with soy sauce and sesame oil; serve.",
            "source": "김준희",
            "image_url": None,
            "ingredients": [
                ("배추김치", "1컵", False),
                ("밥", "2공기", False),
                ("식용유", "2큰술", False),
                ("간장", "1큰술", True),
                ("참기름", "1큰술", True),
                ("계란", "1개", True),
            ],
        },
        {
            "id": 4,
            "title": "그릭요거트볼",
            "slug": "greek-yogurt-bowl",
            "category": "Western",
            "description": "그릭요거트에 과일과 그레놀라를 얹은 간단한 아침 식사.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "breakfast",
            "dietary_tags": ["Vegetarian"],
            "rating": 4.4,
            "cooking_time_minutes": 5,
            "serving_size": 1,
            "instructions": "1. 그릭요거트를 1인이 먹을 양만큼 그릇에 덜어낸다.\n2. 그래놀라와 과일을 얹어주고, 꿀을 뿌려서 먹는다.",
            "instructions_en": "1. Scoop one serving of Greek yogurt into a bowl.\n2. Top with granola and fruit; drizzle with honey and serve.",
            "source": "주다인",
            "image_url": None,
            "ingredients": [
                ("그릭요거트", "1인분", False),
                ("과일(블루베리 등)", "적당량", False),
                ("그레놀라", "적당량", False),
                ("꿀", "적당량", True),
            ],
        },
        {
            "id": 5,
            "title": "김치찜",
            "slug": "kimchi-jjim",
            "category": "Korean",
            "description": "묵은지와 목살을 함께 쪄낸 깊고 진한 맛의 김치찜.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "dinner",
            "dietary_tags": ["Spicy"],
            "rating": 4.8,
            "cooking_time_minutes": 40,
            "serving_size": 1,
            "instructions": "1. 양파는 껍질을 벗긴 뒤 냄비 바닥에 깔 수 있도록 큼직하게 썬다.\n2. 냄비에 올리브유를 둘러 바닥에 골고루 발라준다.\n3. 팬을 예열한 뒤 고기를 넣고 앞뒤로 노릇하게 구워준다.\n4. 고기가 다 구워지면 따로 빼두고, 냄비 바닥에 썰어둔 양파를 깐다.\n5. 그 위에 구운 고기를 올린 후에 김치를 올려 고기가 완전히 덮이도록 한다.\n6. 냄비 바닥에서 보글보글 끓는 소리가 나기 시작하면 물을 부어준다.\n7. 통마늘, 진간장, 코인육수를 넣고 뚜껑을 덮고 중불에서 10분간 끓인다.\n8. 대파를 넣고 중약불로 줄여 20분 더 끓인다.\n9. 마지막으로 다진 마늘 1큰술을 넣어 마무리한다.",
            "instructions_en": "1. Peel onion; cut into large rounds to layer on pot bottom.\n2. Coat pot with olive oil.\n3. Preheat pan and sear meat on both sides until golden.\n4. Remove cooked meat; layer sliced onion on pot bottom.\n5. Place seared meat on top; cover completely with kimchi. Keep heat on.\n6. When bubbling, add water.\n7. Add whole garlic, soy sauce, and broth cube; cover; cook medium 10 minutes.\n8. Add green onions; reduce to medium-low; cook 20 more minutes.\n9. Finish with 1 tbsp minced garlic.",
            "source": "박수정",
            "image_url": None,
            "ingredients": [
                ("돼지고기(목살)", "500g", False),
                ("묵은지", "500g", False),
                ("양파", "1개", False),
                ("마늘", "한 줌", False),
                ("대파", "1대", False),
                ("올리브유", "2큰술", False),
                ("진간장", "1~2큰술", False),
                ("코인육수", "1개", True),
                ("알룰로스", "약간", True),
            ],
        },
        {
            "id": 6,
            "title": "또띠아 랩",
            "slug": "tortilla-wrap",
            "category": "Western",
            "description": "볶은 다짐육과 요거트 소스를 넣어 구운 또띠아 랩.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.3,
            "cooking_time_minutes": 30,
            "serving_size": 1,
            "instructions": "1. 팬에 오일을 두르고 다짐육을 넣은 뒤, 시즈닝 가루, 파프리카 가루, 후추를 더해 볶는다. 케찹과 스리라차 소스를 넣고 한 번 더 볶는다.\n2. 양파는 채 썰어 물에 담가 준비한다.\n3. 그릭요거트에 마요네즈, 다진 마늘, 파슬리, 레몬즙, 딜을 넣어 요거트 소스를 만든다.\n4. 양파에 레몬즙, 파프리카 가루, 파슬리를 넣어 양파절임을 만든다.\n5. 또띠아에 요거트 소스, 채소, 볶은 다짐육, 양파절임, 토마토, 타코 소스 순으로 올린다.\n6. 또띠아를 접어 올리브 오일을 바르고 팬에 노릇하게 굽는다.",
            "instructions_en": "1. Stir-fry ground meat in oiled pan with seasoning, paprika powder, and pepper. Add ketchup and sriracha; stir-fry once more.\n2. Slice onion; soak in water.\n3. Mix Greek yogurt with mayonnaise, garlic, parsley, lemon juice, and dill to make yogurt sauce.\n4. Add lemon juice, paprika powder, and parsley to soaked onion; mix to make pickled onion.\n5. Spread yogurt sauce on center of tortilla; layer vegetables, cooked meat, pickled onion, tomato, and taco sauce.\n6. Fold tortilla neatly; brush olive oil on folded edges; pan-fry until golden.",
            "source": "주다인",
            "image_url": None,
            "ingredients": [
                ("돼지고기(다짐육)", "100g", False),
                ("또띠아", "1장", False),
                ("그릭요거트", "2큰술", False),
                ("마요네즈", "1큰술", False),
                ("마늘", "1작은술", False),
                ("양파", "½개", False),
                ("토마토", "½개", False),
                ("양배추", "적당량", True),
                ("시즈닝가루", "적당량", False),
                ("케찹", "1큰술", True),
                ("스리라차", "1큰술", True),
                ("올리브유", "1큰술", False),
                ("파슬리", "약간", True),
                ("딜", "약간", True),
            ],
        },
        {
            "id": 7,
            "title": "참치비빔우동",
            "slug": "tuna-bibim-udon",
            "category": "Korean",
            "description": "참치와 마요네즈, 쯔유로 비벼 먹는 간단한 우동.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.5,
            "cooking_time_minutes": 10,
            "serving_size": 1,
            "instructions": "1. 우동면을 1분 삶고 물기를 빼준다.\n2. 그릇에 우동면, 쯔유 1스푼, 기름 뺀 참치 1 작은 캔, 마요네즈 2~3스푼 넣고 비벼준다.\n3. 잘게 썬 대파, 김가루, 깨를 뿌려준다.\n4. 취향껏 와사비나 트러플 오일을 뿌려준다.",
            "instructions_en": "1. Boil udon for 1 minute; drain well.\n2. In a bowl, combine udon, 1 tbsp tsuyu, 1 can oil-drained tuna, and 2-3 tbsp mayonnaise; toss well.\n3. Top with finely chopped green onion, shredded seaweed, and sesame seeds.\n4. Add wasabi or truffle oil to taste.",
            "source": "tasty_d.ay",
            "image_url": None,
            "ingredients": [
                ("우동면", "1인분", False),
                ("참치(캔)", "1캔", False),
                ("마요네즈", "2~3큰술", False),
                ("쯔유", "1큰술", False),
                ("대파", "약간", True),
                ("김가루", "약간", True),
                ("깨", "약간", True),
                ("와사비", "약간", True),
                ("트러플오일", "약간", True),
            ],
        },
        {
            "id": 8,
            "title": "비빔라면",
            "slug": "bibim-ramen",
            "category": "Korean",
            "description": "마요네즈와 계란 노른자로 비벼 먹는 색다른 라면.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "lunch",
            "dietary_tags": ["Spicy"],
            "rating": 4.4,
            "cooking_time_minutes": 10,
            "serving_size": 1,
            "instructions": "1. 그릇에 마요네즈, 라면스프, 쪽파, 마늘, 계란 노른자를 1:1:1:1 비율로 모두 섞어준다.\n2. 라면을 삶아서 나온 면수를 1국자 퍼서 그릇에 추가해준다.\n3. 라면을 건져서 그릇에 넣고 비벼준다.",
            "instructions_en": "1. Mix mayonnaise, ramen seasoning, green onion, garlic, and egg yolk in a bowl in 1:1:1:1 ratio.\n2. Add 1 ladle of noodle cooking water to the bowl.\n3. Drain cooked noodles; add to bowl and toss well.",
            "source": "matdori.world",
            "image_url": None,
            "ingredients": [
                ("라면 면발", "1인분", False),
                ("마요네즈", "적당량", False),
                ("계란", "1개 (노른자만)", False),
                ("쪽파", "약간", True),
                ("마늘", "약간", True),
            ],
        },
        {
            "id": 9,
            "title": "양념갈비",
            "slug": "yangnyeom-galbi",
            "category": "Korean",
            "description": "간장 양념에 재워 구운 부드러운 소갈비.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "dinner",
            "dietary_tags": [],
            "rating": 4.8,
            "cooking_time_minutes": 90,
            "serving_size": 4,
            "instructions": "준비하기\n1. 소갈비는 연한 암소 갈비를 골라 하얀 기름 덩어리와 질긴 껍질을 떼어낸다. 살을 0.6cm 두께로 저며서 잔칼집을 넣는다.\n2. 선택 양념 재료인 양파, 배, 사과, 마늘, 생강을 믹서에 넣고 곱게 간다.\n3. 냄비에 양념장 재료를 모두 넣고 중간 불에서 설탕이 녹을 때까지 끓여 식힌 다음 갈아놓은 선택 양념을 섞는다.\n4. 손질한 소갈비를 양념장에 버무려 1시간 정도 재워둔다.\n조리하기\n5. 갈비를 180℃로 예열한 오븐에 15분 정도 굽거나, 뜨겁게 달군 팬에 얹고 양면을 고루 익힌다.",
            "instructions_en": "Preparation:\n1. Trim beef ribs; score meat 0.6cm thick.\n2. Blend optional sauce ingredients (onion, pear, apple, garlic, ginger) until smooth.\n3. Combine all marinade ingredients in pot; simmer over medium heat until sugar dissolves; cool; mix in blended sauce.\n4. Coat ribs with marinade; marinate 1 hour.\nCooking:\n5. Grill in 180°C oven for 15 minutes, or cook in a hot pan until both sides are cooked. Brush with remaining marinade while grilling.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("소갈비", "1kg", False),
                ("간장", "⅔컵", False),
                ("설탕", "4큰술", False),
                ("물엿", "2큰술", False),
                ("청주", "2큰술", False),
                ("양파", "½개", True),
                ("배", "100g", True),
                ("사과", "½개", True),
                ("마늘", "5쪽", True),
                ("생강", "1쪽", True),
            ],
        },
        {
            "id": 10,
            "title": "오리구이",
            "slug": "ori-gui",
            "category": "Korean",
            "description": "참기름과 청주로 밑간한 오리 고기를 노릇하게 구운 요리.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "dinner",
            "dietary_tags": [],
            "rating": 4.5,
            "cooking_time_minutes": 40,
            "serving_size": 4,
            "instructions": "준비하기\n1. 오리 고기는 소금, 후춧가루, 참기름, 청주를 넣고 주물러서 20분 동안 재운다.\n2. 된장에 나머지 재료를 섞어서 쌈된장을 만든다.\n3. 겨잣가루에 물을 넣고 따뜻하게 10분 정도 두어 매운맛이 나면 식초, 소금, 설탕을 섞는다.\n조리하기\n4. 뜨겁게 달군 석쇠나 팬에 재워둔 오리 고기를 얹고 노릇하게 구워낸다.\n5. 오리구이는 겨자장이나 쌈된장을 찍어서 채소에 싸 먹는다.",
            "instructions_en": "Preparation:\n1. Season duck with salt, pepper, sesame oil, and cheongju; marinate 20 minutes.\n2. Mix doenjang with remaining ingredients for ssam sauce.\n3. Mix mustard powder with warm water; let sit 10 minutes until spicy; add vinegar, salt, and sugar.\nCooking:\n4. Grill marinated duck on a hot grill or pan until golden.\n5. Serve with mustard sauce or ssam sauce, wrapped in vegetables.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("오리 고기", "500g", False),
                ("소금", "1작은술", False),
                ("후춧가루", "약간", False),
                ("참기름", "1큰술", False),
                ("청주", "1큰술", False),
                ("된장", "½컵", False),
                ("고추장", "⅓컵", False),
                ("풋고추", "½컵", True),
                ("식초", "2큰술", True),
                ("설탕", "1½큰술", True),
            ],
        },
        {
            "id": 11,
            "title": "닭갈비",
            "slug": "dak-galbi",
            "category": "Korean",
            "description": "매콤한 양념에 닭다리 살과 채소를 볶아 만드는 춘천식 닭갈비.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "dinner",
            "dietary_tags": ["Spicy"],
            "rating": 4.7,
            "cooking_time_minutes": 40,
            "serving_size": 4,
            "instructions": "준비하기\n1. 닭다리 살을 5cm 크기로 큼직하게 썬다.\n2. 고추장에 나머지 재료를 섞어서 양념장을 만든다.\n3. 고구마와 당근은 길이 5cm, 폭 1cm로 썬다.\n4. 양배추와 양파는 1cm 굵기로 썬다.\n5. 대파와 떡볶이 떡은 5cm 길이로 썬다.\n조리하기\n6. 손질한 닭다리 살을 양념장에 버무린다.\n7. 뜨겁게 달군 팬에 식용유를 두르고 중간 불에서 양념한 닭다리 살과 채소를 넣어 타지 않게 저어가며 볶는다.",
            "instructions_en": "Preparation:\n1. Cut chicken thigh into 5cm pieces.\n2. Mix gochujang with remaining marinade ingredients.\n3. Cut sweet potato and carrot into 5cm × 1cm strips.\n4. Cut cabbage and onion into 1cm-wide strips.\n5. Cut green onion and rice cakes into 5cm pieces.\nCooking:\n6. Coat chicken in marinade.\n7. Heat oiled pan over medium heat; stir-fry marinated chicken and vegetables, stirring to prevent burning. Serve when fully cooked.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("닭다리 살", "480g", False),
                ("떡볶이 떡", "120g", False),
                ("고구마", "90g", False),
                ("양배추", "4장", False),
                ("당근", "60g", False),
                ("마늘", "12쪽", False),
                ("양파", "¾개", False),
                ("대파", "1대", False),
                ("고추장", "4큰술", False),
                ("고춧가루", "2큰술", False),
                ("카레가루", "1큰술", False),
                ("간장", "2큰술", False),
                ("물엿", "2큰술", False),
                ("청주", "2큰술", False),
                ("설탕", "1큰술", False),
                ("참기름", "1큰술", False),
                ("식용유", "3큰술", False),
            ],
        },
        {
            "id": 12,
            "title": "떡갈비",
            "slug": "tteok-galbi",
            "category": "Korean",
            "description": "갈빗살을 다져 뼈에 붙여 모양을 낸 궁중식 떡갈비.",
            "cooking_level": "advanced",
            "difficulty": "hard",
            "meal_type": "dinner",
            "dietary_tags": [],
            "rating": 4.6,
            "cooking_time_minutes": 60,
            "serving_size": 4,
            "instructions": "준비하기\n1. 소갈비는 기름기를 제거하고 살만 발라낸다. 갈빗살을 곱게 다진 뒤 키친타월로 꼭꼭 눌러 핏물을 제거한다.\n2. 갈비뼈는 끓는 물에 넣고 5분 동안 삶아서 뼈에 붙은 살을 제거한다.\n3. 간장에 나머지 재료를 섞어서 양념장을 만든다.\n4. 부추는 5cm 길이로 썬다.\n조리하기\n5. 다진 갈빗살을 양념장에 버무려서 찹쌀가루를 넣고 치대어 반죽한다.\n6. 갈비뼈에 밀가루를 바르고 갈빗살을 둥글게 붙인다.\n7. 뜨겁게 달군 팬이나 석쇠에 얹어서 양면을 고루 익힌다.\n8. 구운 고기를 접시에 담고 부추와 잣가루를 곁들여 낸다.",
            "instructions_en": "Preparation:\n1. Remove fat from ribs; finely mince the meat; press with kitchen paper to remove blood.\n2. Boil rib bones in boiling water 5 minutes to clean.\n3. Mix soy sauce with remaining ingredients for marinade.\n4. Cut garlic chives into 5cm pieces.\nCooking:\n5. Mix minced rib meat with marinade and glutinous rice flour; knead into a dough.\n6. Dust rib bones with flour; press dough onto bones in a round shape.\n7. Cook both sides on a hot pan or grill until done.\n8. Serve topped with garlic chives and pine nut powder.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("소갈비", "1kg", False),
                ("찹쌀가루", "3큰술", False),
                ("밀가루", "3큰술", False),
                ("부추", "60g", True),
                ("잣가루", "3큰술", True),
                ("간장", "1큰술", False),
                ("소금", "2작은술", False),
                ("배", "1큰술(간 것)", True),
                ("청주", "½큰술", False),
                ("대파", "1큰술(다진)", False),
                ("마늘", "½큰술(다진)", False),
                ("참기름", "1큰술", False),
                ("깨소금", "1작은술", False),
            ],
        },
        {
            "id": 13,
            "title": "두부김치",
            "slug": "dubu-kimchi",
            "category": "Korean",
            "description": "삶은 두부와 볶은 김치를 함께 곁들여 먹는 안주.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "dinner",
            "dietary_tags": ["Spicy"],
            "rating": 4.5,
            "cooking_time_minutes": 25,
            "serving_size": 4,
            "instructions": "준비하기\n1. 잘 익은 배추김치를 2.5cm 폭으로 썬다.\n2. 돼지고기를 0.3cm 두께로 얇게 썬 후 한 입 크기로 썬다.\n3. 양파는 길이로 채 썬다.\n4. 양념 재료를 모두 섞은 뒤 돼지고기를 넣고 30분 동안 재워둔다.\n조리하기\n5. 두부는 반으로 자른 후 냄비에 담아 물과 소금을 넣고 약한 불에서 5분간 삶는다. 1cm 두께로 썰어 접시에 담아둔다.\n6. 충분히 달군 프라이팬에 식용유를 두르고 양념한 돼지고기를 볶는다.\n7. 돼지고기가 반 정도 익으면 배추김치와 양파를 넣고 볶는다. 완전히 볶아지면 참기름을 둘러 두부와 함께 낸다.",
            "instructions_en": "Preparation:\n1. Cut kimchi into 2.5cm-wide pieces.\n2. Slice pork 0.3cm thick; cut into bite-sized pieces.\n3. Julienne onion.\n4. Mix all seasoning ingredients; add pork; marinate 30 minutes.\nCooking:\n5. Boil tofu in water with salt on low heat for 5 minutes; slice 1cm thick and plate.\n6. Stir-fry seasoned pork in oiled pan.\n7. When pork is half-cooked, add kimchi and onion; stir-fry until done. Drizzle sesame oil and serve alongside tofu.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("배추김치", "250g", False),
                ("돼지고기(삼겹살)", "150g", False),
                ("두부", "1모(300g)", False),
                ("양파", "½개", False),
                ("고춧가루", "½큰술", False),
                ("고추장", "½큰술", False),
                ("간장", "1큰술", False),
                ("설탕", "2큰술", False),
                ("마늘", "½작은술(다진)", False),
                ("참기름", "1큰술", False),
                ("깨소금", "1큰술", True),
                ("식용유", "2큰술", False),
            ],
        },
        {
            "id": 14,
            "title": "소면 비빔",
            "slug": "somyeon-bibim",
            "category": "Korean",
            "description": "간장 양념장에 비벼 먹는 시원한 소면.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.3,
            "cooking_time_minutes": 15,
            "serving_size": 1,
            "instructions": "1. 끓는 물에 소면을 넣고 삶는다.\n2. 면을 삶는 동안 양념 재료를 모두 섞어서 양념장을 만들어준다.\n3. 삶아진 소면은 차가운 물에 헹궈서 전분기를 뺀다.\n4. 소면에다가 양념장을 붓고 채 썬 청양고추, 김가루, 계란 노른자, 참기름, 깨 등을 취향껏 얹어서 비벼준다.",
            "instructions_en": "1. Boil noodles in boiling water.\n2. While noodles cook, mix all sauce ingredients.\n3. Rinse cooked noodles in cold water; drain.\n4. Pour sauce over noodles; top with julienned cheongyang chili, shredded seaweed, egg yolk, sesame oil, and sesame seeds to taste; toss and serve.",
            "source": "주다인",
            "image_url": None,
            "ingredients": [
                ("소면", "1인분", False),
                ("진간장", "4큰술", False),
                ("설탕", "2큰술", False),
                ("올리고당", "1큰술", False),
                ("마늘", "1큰술(다진)", False),
                ("참기름", "1큰술", False),
                ("깨", "1큰술", True),
                ("청양고추", "1개", True),
                ("김가루", "약간", True),
                ("계란", "1개", True),
            ],
        },
        {
            "id": 15,
            "title": "소고기떡국",
            "slug": "sogogi-tteokguk",
            "category": "Korean",
            "description": "소고기와 코인육수로 깊은 맛을 낸 떡국.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.6,
            "cooking_time_minutes": 25,
            "serving_size": 1,
            "instructions": "1. 떡국떡은 흐르는 물에 씻은 뒤 채반에 받쳐서 물기를 제거한다.\n2. 대파는 채 썰고 계란은 잘 풀어서 준비한다.\n3. 냄비에 오일과 참기름을 두르고 국거리용 소고기를 넣어서 고기가 절반 정도 익을 때까지 볶아준다.\n4. 물 800ml와 코인육수 1개를 넣고 끓여준다.\n5. 끓는 동안 떠오르는 불순물들은 깨끗하게 제거해준다.\n6. 손질한 떡국떡을 넣고 떡이 말랑해질 때까지 푹 끓여준다.\n7. 대파와 풀어둔 계란물을 넣고, 소금은 반 스푼 넣은 후 조금 더 끓여서 완성해준다.\n8. 그릇에 담아서 김가루와 깨를 뿌리고, 취향껏 참기름을 살짝 둘러서 마무리 해준다.",
            "instructions_en": "1. Rinse rice cakes under running water; drain.\n2. Julienne green onion; beat egg.\n3. In a pot, heat oil and sesame oil; add stew beef; stir-fry until half-cooked.\n4. Add 800ml water and 1 broth cube; bring to a boil.\n5. Skim off impurities.\n6. Add rice cakes; boil until soft.\n7. Add green onion, beaten egg, and ½ tsp salt; cook a bit more.\n8. Serve topped with shredded seaweed and sesame seeds; optionally drizzle sesame oil.",
            "source": "주다인",
            "image_url": None,
            "ingredients": [
                ("국거리용 소고기", "120~130g", False),
                ("떡볶이 떡", "200g", False),
                ("코인육수", "1개", False),
                ("계란", "1개", False),
                ("대파", "적당량", False),
                ("참기름", "약간", False),
                ("식용유", "약간", False),
                ("소금", "½작은술", False),
                ("김가루", "약간", True),
                ("깨", "약간", True),
            ],
        },
        {
            "id": 16,
            "title": "마녀스프",
            "slug": "witch-soup",
            "category": "Western",
            "description": "토마토퓨레와 다양한 채소, 소고기를 넣어 끓인 든든한 스프.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "dinner",
            "dietary_tags": [],
            "rating": 4.4,
            "cooking_time_minutes": 30,
            "serving_size": 1,
            "instructions": "1. 야채들과 소고기를 먹기 좋은 크기로 썰어준다.\n2. 냄비에 올리브유를 두르고 간마늘과 고기, 양파를 넣고 볶아준다. 매콤한 맛을 원한다면 이때 페페론치노 3개를 추가한다.\n3. 재료들이 반 정도 익으면 딱딱한 재료인 감자와 당근을 먼저 넣고, 이어서 양배추, 토마토, 새송이버섯을 차례로 넣고 볶아준다.\n4. 모든 재료를 적당히 볶았다면, 토마토퓨레와 물, 월계수잎을 넣고 약한 불에서 끓여준다.\n5. 마지막으로 카레가루 2스푼을 넣어서 풍미를 더해준다.\n6. 그릇에 담아서 파마산 치즈 가루를 뿌려서 마무리한다.",
            "instructions_en": "1. Cut vegetables and beef into bite-sized pieces.\n2. Heat olive oil in a pot; add garlic, meat, and onion; stir-fry. Add peperoncino for a spicy kick.\n3. When half-cooked, add potato and carrot first; then cabbage, tomato, and mushroom.\n4. After stir-frying, add tomato purée, water, and bay leaves; simmer on low heat.\n5. Add 2 tbsp curry powder for flavor.\n6. Serve topped with parmesan cheese.",
            "source": "yun_cha_cha_daily",
            "image_url": None,
            "ingredients": [
                ("양배추", "2줌", False),
                ("토마토", "2개", False),
                ("양파", "¼개", False),
                ("당근", "⅓개", False),
                ("감자", "1개", False),
                ("새송이버섯", "1개", False),
                ("국거리용 소고기", "1팩", False),
                ("토마토퓨레", "2컵", False),
                ("월계수잎", "2~3장", False),
                ("카레가루", "2큰술", False),
                ("마늘", "1큰술(다진)", False),
                ("올리브유", "약간", False),
                ("페페론치노", "3개", True),
                ("파마산 치즈", "약간", True),
            ],
        },
        {
            "id": 17,
            "title": "두부조림",
            "slug": "dubu-jorim",
            "category": "Korean",
            "description": "노릇하게 지진 두부를 간장 양념장에 조린 반찬.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "dinner",
            "dietary_tags": ["Vegetarian"],
            "rating": 4.5,
            "cooking_time_minutes": 20,
            "serving_size": 4,
            "instructions": "준비하기\n1. 두부는 4×3×0.6cm 도톰한 사각형으로 썰고 소금을 뿌려서 5분 정도 둔다.\n2. 간장에 나머지 재료를 섞어서 조림 양념장을 만든다.\n조리하기\n3. 두부는 키친타월로 물기를 걷는다.\n4. 뜨겁게 달군 팬에 식용유와 참기름을 두르고 두부를 노릇하게 지진다.\n5. 냄비에 두부를 한 켜 깔고 그 위에 조림 양념장을 고루 끼얹은 뒤 다시 두부를 한 켜 올리고 남은 양념장을 모두 끼얹는다. 물 ½컵을 붓고 불에 올려 끓인다.\n6. 양념장 물이 끓어오르면 불을 줄이고 수시로 양념장 물을 끼얹어가며 국물이 거의 없어질 때까지 두부를 조린다.",
            "instructions_en": "Preparation:\n1. Cut tofu into thick rectangles (~4×3×0.6cm); sprinkle salt; let sit 5 minutes.\n2. Mix soy sauce with remaining ingredients for braising sauce.\nCooking:\n3. Pat tofu dry with kitchen paper.\n4. Pan-fry in oiled pan until golden on both sides.\n5. Layer tofu in a pot; pour sauce over; layer more tofu; pour remaining sauce; add ½ cup water; bring to a boil.\n6. Reduce heat; spoon sauce over tofu repeatedly until sauce is almost gone.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("두부", "1모(300g)", False),
                ("간장", "3큰술", False),
                ("고춧가루", "1작은술", False),
                ("설탕", "1큰술", False),
                ("대파", "1큰술(다진)", False),
                ("마늘", "1작은술(다진)", False),
                ("참기름", "1큰술", False),
                ("깨소금", "1큰술", True),
                ("식용유", "1큰술", False),
                ("소금", "½큰술", False),
            ],
        },
        {
            "id": 18,
            "title": "제육덮밥",
            "slug": "jeyuk-deopbap",
            "category": "Korean",
            "description": "매콤한 고추장 양념에 볶은 제육볶음을 밥 위에 올린 덮밥.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "dinner",
            "dietary_tags": ["Spicy"],
            "rating": 4.7,
            "cooking_time_minutes": 25,
            "serving_size": 4,
            "instructions": "준비하기\n고추장에 나머지 재료를 섞어서 양념장을 만든다.\n돼지고기는 한 입 크기로 썰고 양념장의 반을 덜어서 무친다.\n양배추, 당근, 양파는 3×1×0.3cm 크기로 썬다.\n대파와 고추는 어슷하게 썰고, 마늘은 편으로 썬다.\n조리하기\n뜨겁게 달군 팬에 식용유 1큰술을 두르고 준비된 양파, 양배추, 당근, 고추, 대파를 센 불에서 양념장의 반을 넣고 반 정도 익게 볶아낸다.\n뜨겁게 달군 팬에 식용유 1큰술을 두르고 마늘편, 돼지고기를 넣어 고기가 익을 때까지 센 불에서 볶은 후 채소와 섞는다.\n그릇에 밥을 담고 제육볶음을 올린다.",
            "instructions_en": "Preparation:\nMix gochujang with remaining sauce ingredients.\nCut pork into bite-sized pieces; coat with half the sauce.\nCut cabbage, carrot, and onion into 3×1×0.3cm pieces.\nSlice green onion and chilies diagonally; slice garlic thinly.\nCooking:\nHeat pan with 1 tbsp oil; stir-fry vegetables with remaining sauce on high heat until half-cooked.\nHeat pan with 1 tbsp oil; stir-fry garlic and pork on high heat until cooked; mix with vegetables.\nServe over rice.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("밥", "4공기", False),
                ("돼지고기(목살)", "300g", False),
                ("양배추", "150g", False),
                ("양파", "½개", False),
                ("풋고추", "2개", True),
                ("홍고추", "1개", True),
                ("당근", "15g", False),
                ("대파", "1대", False),
                ("마늘", "4쪽", False),
                ("고추장", "1큰술", False),
                ("고춧가루", "4큰술", False),
                ("간장", "2큰술", False),
                ("설탕", "1큰술", False),
                ("물엿", "2큰술", False),
                ("청주", "2큰술", False),
                ("참기름", "1큰술", False),
                ("식용유", "2큰술", False),
            ],
        },
        {
            "id": 19,
            "title": "콩나물밥",
            "slug": "kongnamul-bap",
            "category": "Korean",
            "description": "콩나물과 고기를 함께 넣어 지은 밥에 양념 간장을 곁들여 비벼 먹는 요리.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.5,
            "cooking_time_minutes": 50,
            "serving_size": 4,
            "instructions": "준비하기\n쌀은 깨끗이 씻어 30분 동안 불린 뒤 체에 건져 물기를 뺀다.\n소고기나 돼지고기 살코기를 곱게 채 썰어 청주와 간장으로 밑간한다.\n콩나물은 꼬리를 떼고 씻어서 건져둔다.\n간장에 나머지 재료를 섞어서 양념 간장을 만든다.\n조리하기\n냄비에 콩나물을 반 깔고 고기를 얹은 뒤 쌀을 안친다. 다시 콩나물, 고기를 얹고 물 2컵을 붓는다.\n처음엔 센 불에서 끓이다 콩나물 익는 냄새가 나면 약한 불에서 8분 정도 더 끓인다. 불을 끄고 10분간 뜸을 들인다.\n그릇에 콩나물밥을 담고 양념 간장을 넣어서 비벼 먹는다.",
            "instructions_en": "Preparation:\nWash rice; soak 30 minutes; drain.\nFinely julienne meat; season with cheongju and soy sauce.\nTrim bean sprout tails; wash and drain.\nMix seasoning soy sauce ingredients together.\nCooking:\nLayer half bean sprouts in a pot; add meat; add rice. Layer remaining bean sprouts and meat; add 2 cups water.\nBoil on high heat; when bean sprout smell rises, reduce to low heat 8 minutes. Turn off heat; steam 10 minutes. Mix with rice paddle.\nServe with seasoning soy sauce.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("멥쌀", "2컵(450g)", False),
                ("국거리용 소고기", "100g", False),
                ("콩나물", "300g", False),
                ("간장", "5큰술(양념장)", False),
                ("청주", "½큰술", False),
                ("고춧가루", "2큰술", True),
                ("풋고추", "2큰술(다진)", True),
                ("실파", "15g", True),
                ("마늘", "1작은술(다진)", True),
                ("참기름", "1큰술", False),
                ("깨소금", "1작은술", True),
            ],
        },
        {
            "id": 20,
            "title": "불고기덮밥",
            "slug": "bulgogi-deopbap",
            "category": "Korean",
            "description": "달콤한 간장 양념 불고기를 당면, 느타리버섯과 함께 밥 위에 올린 덮밥.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "dinner",
            "dietary_tags": [],
            "rating": 4.6,
            "cooking_time_minutes": 40,
            "serving_size": 4,
            "instructions": "준비하기\n소고기는 2mm 두께의 등심으로 준비한다. 키친타월로 핏물을 눌러서 걷어낸다.\n간장에 나머지 재료를 합해서 양념장을 만든다.\n당면은 미지근한 물에 30분 정도 불려서 건진다.\n양파는 반 갈라서 채 썰고, 피망과 홍고추는 씨를 빼고 채 썬다.\n느타리버섯은 굵게 찢어둔다.\n조리하기\n뜨겁게 달군 팬에 양념한 소고기를 넣고 중간 불에서 볶다가 양파, 피망을 넣어 양파가 투명해질 때까지 볶는다.\n당면을 넣고 5분간 볶은 다음 홍고추와 느타리버섯을 넣고 5분간 더 볶는다.\n접시에 밥을 담고 불고기를 곁들여 낸다.",
            "instructions_en": "Preparation:\nPrepare 2mm-thick sirloin slices; blot with kitchen paper.\nMix soy sauce with remaining ingredients for sauce.\nSoak glass noodles in lukewarm water 30 minutes; drain.\nHalve and julienne onion; seed and julienne bell pepper and chili.\nRoughly tear oyster mushrooms.\nCooking:\nStir-fry seasoned beef in a hot pan over medium; add onion and bell pepper; cook until onion is translucent.\nAdd glass noodles; stir-fry 5 minutes; add chili and mushrooms; cook 5 more minutes.\nServe over rice.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("밥", "4공기", False),
                ("소고기(등심)", "450g", False),
                ("양파", "1개", False),
                ("피망", "1개", True),
                ("홍고추", "1개", True),
                ("당면", "30g", False),
                ("느타리버섯", "100g", False),
                ("간장", "4큰술", False),
                ("설탕", "3큰술", False),
                ("물엿", "2큰술", False),
                ("대파", "2큰술(다진)", False),
                ("마늘", "1큰술(다진)", False),
                ("후춧가루", "약간", False),
            ],
        },
        {
            "id": 21,
            "title": "비빔밥",
            "slug": "bibimbap",
            "category": "Korean",
            "description": "표고버섯, 시금치, 콩나물, 소고기 볶음을 밥 위에 얹어 고추장과 비벼 먹는 전통 비빔밥.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.8,
            "cooking_time_minutes": 40,
            "serving_size": 4,
            "instructions": "준비하기\n표고버섯은 기둥을 제거하고 가늘게 채 썬다.\n시금치와 콩나물은 다듬어 깨끗이 씻어놓는다.\n소고기 볶음 재료를 모두 섞은 뒤 소고기를 넣고 5분 동안 재운다.\n조리하기\n뜨겁게 달군 팬에 식용유를 두르고 채 썬 표고버섯을 소금간하여 볶는다.\n물 3컵을 끓여서 소금을 약간 넣고 시금치를 1분 동안 데친다. 찬물에 헹궈 물기를 짠 다음 양념 재료를 넣어 무친다.\n콩나물은 냄비에 담고 물 1½컵을 부어 소금을 약간 넣은 뒤 15분 동안 뚜껑을 닫고 약한 불에서 삶는다. 소금과 참기름으로 양념한다.\n뜨겁게 달군 팬에 양념한 소고기를 넣고 익을 때까지 볶는다.\n밥을 각자의 그릇에 나누어 담고 준비한 나물과 소고기 볶음을 나란히 얹는다. 고추장과 참기름은 따로 담아낸다.",
            "instructions_en": "Preparation:\nRemove shiitake stems; julienne finely.\nTrim spinach and bean sprouts.\nMix beef seasoning; coat beef; marinate 5 minutes.\nCooking:\nStir-fry shiitake with salt in oiled pan.\nBlanch spinach 1 minute in salted boiling water; rinse in cold water; squeeze dry; season.\nSimmer bean sprouts with water and salt covered on low heat 15 minutes; season.\nStir-fry seasoned beef until cooked.\nDivide rice into bowls; arrange shiitake, spinach, bean sprouts, and beef alongside each other. Serve gochujang and sesame oil on the side.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("밥", "4공기", False),
                ("표고버섯", "5개", False),
                ("시금치", "150g", False),
                ("콩나물", "150g", False),
                ("다진 소고기", "150g", False),
                ("간장", "1큰술", False),
                ("설탕", "½큰술", False),
                ("참기름", "1큰술", False),
                ("깨소금", "1작은술", True),
                ("고추장", "적당량", False),
                ("식용유", "1작은술", False),
            ],
        },
        {
            "id": 22,
            "title": "주먹밥",
            "slug": "jumeok-bap",
            "category": "Korean",
            "description": "잔멸치볶음, 우엉조림, 구운 김을 섞어 동그랗게 빚은 주먹밥.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.3,
            "cooking_time_minutes": 30,
            "serving_size": 4,
            "instructions": "준비하기\n뜨거운 밥에 참기름을 섞어 주걱으로 버무리고 한김 식힌다.\n우엉은 껍질을 벗기고 곱게 다진다. 팬에 우엉 조림장을 붓고 센 불로 끓이다 우엉을 넣고 약한 불에서 물기가 없어질 때까지 볶은 다음 접시에 펼쳐놓고 식힌다.\n구운 김은 잘게 부수고, 잔멸치볶음과 우엉조림을 섞는다.\n조리하기\n모든 재료를 다 섞은 다음 주먹으로 60g씩 쥐어 동그랗게 빚는다.",
            "instructions_en": "Preparation:\nMix sesame oil into hot rice; cool slightly.\nPeel and finely mince burdock. Boil braising sauce in pan; add burdock; cook on low until dry. Spread to cool.\nCrumble seaweed; mix with stir-fried anchovies and braised burdock.\nCooking:\nMix all ingredients; form into round 60g balls.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("밥", "4공기", False),
                ("참기름", "1큰술", False),
                ("잔멸치볶음", "60g", False),
                ("구운 김", "2장", False),
                ("우엉", "120g", False),
                ("간장", "1½큰술", False),
                ("물엿", "1큰술", False),
                ("깨", "4작은술", True),
            ],
        },
        {
            "id": 23,
            "title": "김밥",
            "slug": "gimbap",
            "category": "Korean",
            "description": "소고기, 단무지, 오이, 당근, 계란을 넣어 만 든든한 김밥.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.7,
            "cooking_time_minutes": 50,
            "serving_size": 4,
            "instructions": "준비하기\n고슬고슬한 따뜻한 밥에 소금과 참기름을 넣고 버무려서 약간 식힌다.\n다진 소고기는 20분 동안 고기 양념장에 재웠다 뜨겁게 달군 팬에 고기가 익을 때까지 볶는다.\n단무지는 김 길이에 맞춰 썰어 연필 굵기로 썬다.\n오이는 단무지와 같은 길이로 썰어 씨를 빼고 연필 굵기로 썬다. 단촛물에 오이를 30분 정도 담가 절인 뒤 물기를 제거한다.\n당근은 곱게 채 썰어 소금을 조금 넣고 팬에 볶아 식힌다.\n계란은 소금을 조금 넣고 풀어서 도톰하게 부친다.\n조리하기\n김의 매끄러운 부분이 김발에 마주하도록 놓는다. 조미한 밥 1컵을 김 중앙에 올린 다음 김 윗부분의 ¼을 남기고 넓게 편다.\n밥 가운데에 소고기, 단무지, 오이, 당근, 계란을 나란히 놓는다. 김발을 안쪽부터 말면서 꼭꼭 누른다.\n칼에 참기름을 바르고 1cm 두께로 동글게 썬다.",
            "instructions_en": "Preparation:\nMix salt and sesame oil into warm rice; cool.\nMarinate beef 20 minutes; stir-fry until cooked.\nCut pickled radish into pencil-width strips.\nCut cucumber same length; remove seeds; cut pencil-width; soak in sweet vinegar water 30 minutes; squeeze dry.\nJulienne carrot; stir-fry with salt; cool.\nBeat eggs with salt; make thick omelet; cut into same-width strips.\nCooking:\nPlace seaweed rough-side down on bamboo mat. Spread 1 cup rice over ¾ of seaweed.\nArrange beef, pickled radish, cucumber, carrot, and egg side by side in center. Roll from near end, pressing firmly.\nBrush knife with sesame oil; slice into 1cm rounds.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("밥", "4공기", False),
                ("구운 김", "4장", False),
                ("다진 소고기", "200g", False),
                ("단무지", "4줄", False),
                ("오이", "⅔개", False),
                ("당근", "½개", False),
                ("계란", "3개", False),
                ("간장", "2큰술", False),
                ("설탕", "½큰술", False),
                ("참기름", "2큰술", False),
                ("소금", "1작은술", False),
                ("식초", "⅔큰술", True),
            ],
        },
        {
            "id": 24,
            "title": "떡볶이",
            "slug": "tteokbokki",
            "category": "Korean",
            "description": "고추장 양념에 떡과 어묵을 넣어 끓인 국민 간식.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "lunch",
            "dietary_tags": ["Spicy"],
            "rating": 4.8,
            "cooking_time_minutes": 20,
            "serving_size": 4,
            "instructions": "준비하기\n떡볶이 떡은 말랑하면 그냥 씻어 건져두고, 단단히 굳었으면 끓는 물에 살짝 데쳐서 사용한다.\n어묵은 5×2.5cm 크기로 썰어 체에 올려놓고 뜨거운 물을 부어 기름을 뺀다.\n조리하기\n팬에 물을 넣고 양념장을 넣어 잘 푼다.\n팬을 불에 올리고 떡을 넣어 눌어붙지 않게 저어가며 잠시 끓인다.\n어묵을 넣고 양념장이 걸쭉해질 때까지 끓인다.",
            "instructions_en": "Preparation:\nIf rice cakes are soft, simply rinse. If hard, blanch briefly in boiling water.\nCut fish cake into 5×2.5cm pieces; pour hot water over to remove oil.\nCooking:\nAdd water and sauce to pan; stir to dissolve.\nHeat pan; add rice cakes; stir to prevent sticking; simmer briefly.\nAdd fish cake; cook until sauce thickens.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("떡볶이 떡", "500g", False),
                ("어묵", "150g", False),
                ("고추장", "3큰술", False),
                ("간장", "½큰술", False),
                ("설탕", "2큰술", False),
                ("물엿", "1큰술", False),
            ],
        },
        {
            "id": 25,
            "title": "닭볶음탕",
            "slug": "dak-bokkeum-tang",
            "category": "Korean",
            "description": "매콤한 양념에 닭, 감자, 당근을 넣어 끓인 얼큰한 닭볶음탕.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "dinner",
            "dietary_tags": ["Spicy"],
            "rating": 4.7,
            "cooking_time_minutes": 45,
            "serving_size": 4,
            "instructions": "준비하기\n뼈째 토막 낸 닭을 찬물에 씻어 건진 후 물기를 제거하고 청주, 소금, 후춧가루로 밑간하여 20분 동안 재워둔다.\n감자와 당근은 3cm 폭으로 깍둑 썰고, 양파는 반 갈라서 4등분한다.\n실파는 5cm 길이로 썬다.\n홍고추는 1cm 폭으로 어슷하게 썰어 씨를 제거한다.\n고춧가루에 나머지 재료를 섞어서 매운 양념장을 만든다.\n조리하기\n냄비에 닭과 감자, 당근, 양파를 넣고 매운 양념장을 끼얹어 골고루 섞는다. 물 3컵을 부어 센 불에서 끓인다. 끓어오르면 중간 불로 줄여 20분 동안 끓인다.\n국물이 자작하게 줄어들면 실파와 홍고추를 넣고 5분간 더 끓인다.",
            "instructions_en": "Preparation:\nWash chicken; season with cheongju, salt, and pepper; marinate 20 minutes.\nCut potato and carrot into 3cm cubes; quarter onion.\nCut green onions into 5cm lengths.\nSlice red chilies diagonally 1cm wide; remove seeds.\nMix chili powder with remaining ingredients for spicy sauce.\nCooking:\nCombine chicken, potato, carrot, and onion in pot; pour spicy sauce; mix. Add 3 cups water; boil on high heat. Reduce to medium; cook 20 minutes.\nWhen broth reduces, add green onions and red chilies; mix well; cook 5 more minutes.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("닭", "1마리(1kg)", False),
                ("감자", "1개", False),
                ("당근", "½개", False),
                ("양파", "½개", False),
                ("실파", "6대", True),
                ("홍고추", "2개", True),
                ("고춧가루", "4큰술", False),
                ("고추장", "3큰술", False),
                ("간장", "2큰술", False),
                ("청주", "2큰술", False),
                ("설탕", "1큰술", False),
                ("물엿", "2큰술", False),
                ("마늘", "1큰술(다진)", False),
                ("생강", "1작은술(다진)", True),
                ("참기름", "1큰술", False),
                ("후춧가루", "약간", False),
            ],
        },
        {
            "id": 26,
            "title": "만둣국",
            "slug": "manduguk",
            "category": "Korean",
            "description": "직접 빚은 만두를 소고기장국에 넣어 끓인 만둣국.",
            "cooking_level": "advanced",
            "difficulty": "hard",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.6,
            "cooking_time_minutes": 90,
            "serving_size": 4,
            "instructions": "준비하기\n밀가루에 소금을 넣고 체에 친다. 물로 반죽하여 잘 치댄 다음 면포에 싸서 30분 정도 둔다.\n표고버섯은 불려서 가늘게 채 썬다.\n두부는 깨끗한 면포로 싸서 물기를 최대한 짜고 곱게 으깬다.\n숙주는 끓는 물에 데쳐서 물기를 꼭 짜고 송송 썬다.\n배추김치는 잘게 썰어서 국물을 꼭 짠다.\n큰 그릇에 만두소의 재료를 모두 합하고, 양념을 넣어 고루 섞는다.\n계란은 황백 지단으로 부쳐 완자 모양으로 썬다.\n조리하기\n밀가루 반죽을 얇게 밀고 지름 8cm 크기의 둥근 만두피를 만든다.\n둥근 만두피에 소를 놓고 반달 모양으로 빚는다.\n소고기장국을 끓이다 빚은 만두를 넣고 중간 불에서 끓인다. 만두가 떠오르면 대접에 담고 황백 지단을 얹는다.",
            "instructions_en": "Preparation:\nSift flour with salt; knead with water; wrap in cloth; rest 30 minutes.\nRehydrate shiitake; finely julienne.\nWrap tofu in cloth; squeeze out moisture; mash.\nBlanch bean sprouts; squeeze dry; chop.\nFinely chop kimchi; squeeze liquid.\nMix all filling ingredients with seasoning.\nSeparate egg; fry into thin jidan; cut into strips.\nCooking:\nRoll dough thin; cut into 8cm round wrappers.\nFill each wrapper; fold into half-moon shape.\nBring seasoned beef broth to boil; add dumplings; cook over medium heat. When they float, they are cooked. Top with jidan strips.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("밀가루", "1컵", False),
                ("다진 소고기", "150g", False),
                ("마른 표고버섯", "3개", False),
                ("두부", "⅓모", False),
                ("숙주", "90g", False),
                ("배추김치", "90g", False),
                ("계란", "1개", True),
                ("소금", "2작은술", False),
                ("대파", "2큰술(다진)", False),
                ("마늘", "1큰술(다진)", False),
                ("참기름", "1큰술", False),
                ("깨소금", "1큰술", True),
                ("녹말가루", "약간", False),
            ],
        },
        {
            "id": 27,
            "title": "물냉면",
            "slug": "mul-naengmyeon",
            "category": "Korean",
            "description": "동치미 국물과 소고기 육수를 섞은 시원한 냉면.",
            "cooking_level": "advanced",
            "difficulty": "hard",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.7,
            "cooking_time_minutes": 90,
            "serving_size": 4,
            "instructions": "준비하기\n양지머리는 덩어리째 20분 동안 찬물에 담가둔다.\n물 10컵을 냄비에 붓고 소고기, 파, 마늘, 통후추를 넣어 함께 끓인다. 고기가 익으면 건져서 0.3cm 두께로 썰어 편육을 만든다.\n육수는 체에 걸러낸 뒤 식혀서 기름을 걷어낸다.\n무는 0.3cm 두께로 반달썰기해 단촛물에 30분간 담가둔다.\n오이는 어슷하게 썬다. 소금 ½작은술을 뿌려 30분간 절였다가 물기를 짠다.\n배는 껍질을 벗겨 반으로 가른 후 무와 같은 크기로 썬다. 홍고추는 어슷 썬다.\n계란은 12분 동안 삶는다. 껍질을 벗기고 세로로 반을 가른다.\n조리하기\n식힌 소고기 국물과 동치미 국물을 1:1로 합하여 냉면 국물을 만든다.\n큰 냄비에 물을 끓여 메밀면을 3~4분간 삶아서 찬물에 여러 번 헹구고 물기를 뺀다.\n삶은 메밀면을 대접에 담고 소고기 편육, 무, 오이, 배, 홍고추, 계란을 얹는다. 냉면 국물을 부어낸다.",
            "instructions_en": "Preparation:\nSoak brisket in cold water 20 minutes.\nBoil beef with green onion, garlic, and pepper; slice cooked meat thin; strain and cool broth.\nSlice radish thin into half-moons; soak in sweet vinegar water 30 minutes.\nSlice cucumber diagonally; sprinkle salt; pickle 30 minutes; squeeze dry.\nSlice pear same size as radish; slice chili diagonally.\nBoil eggs 12 minutes; peel; halve lengthwise.\nCooking:\nMix beef broth and dongchimi broth 1:1.\nBoil buckwheat noodles; rinse cold several times; drain. Serve in bowls topped with beef, radish, cucumber, pear, chili, and egg. Pour broth from the side; serve condiments on the side.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("냉면용 메밀면", "450g", False),
                ("소고기(양지머리)", "200g", False),
                ("무", "200g", False),
                ("오이", "½개", False),
                ("배", "¼개", True),
                ("홍고추", "1개", True),
                ("계란", "2개", True),
                ("대파", "1대", False),
                ("마늘", "3쪽", False),
                ("후춧가루", "1작은술", False),
                ("식초", "4큰술", False),
                ("설탕", "4큰술", False),
                ("소금", "1큰술", False),
            ],
        },
        {
            "id": 28,
            "title": "간장계란밥",
            "slug": "ganjang-gyeran-bap",
            "category": "Korean",
            "description": "스크램블 계란에 간장과 참기름으로 비벼 반숙 후라이를 올린 간단한 한 끼.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.5,
            "cooking_time_minutes": 10,
            "serving_size": 1,
            "instructions": "1. 계란 2개를 풀어서 후라이팬에 식용유를 넣고 젓가락으로 휘져어 가면서 너무 뭉치지 않게 해주세요.\n2. 에그스크럼블식으로 만든 계란이 되면 가스불을 꺼주세요.\n3. 여기에 따뜻한 밥 1그릇을 넣고, 진간장 1스푼, 참기름 1스푼을 넣고 잘 섞어줍니다.\n4. 계란 1개를 반숙으로 후라이를 해줍니다.\n5. 그릇에 간장계란밥을 올리고 반숙후라이를 올린 후 김을 잘라 올려주시면 완성입니다.",
            "instructions_en": "1. Beat 2 eggs; scramble in oiled pan, stirring with chopsticks to avoid clumping.\n2. Turn off heat; add warm rice.\n3. Add 1 tbsp soy sauce and 1 tbsp sesame oil; mix until combined.\n4. Fry remaining egg sunny-side up, yolk still runny.\n5. Place rice in bowl; top with fried egg; add seaweed strips if available. Done!",
            "source": "10000 recipe",
            "image_url": None,
            "ingredients": [
                ("밥", "1공기", False),
                ("계란", "3개", False),
                ("진간장", "1큰술", False),
                ("참기름", "1큰술", False),
                ("식용유", "2큰술", False),
                ("구운 김", "약간", True),
                ("깨", "약간", True),
            ],
        },
        {
            "id": 29,
            "title": "순두부찌개",
            "slug": "sundubu-jjigae",
            "category": "Korean",
            "description": "순두부와 양파, 대파를 양념에 끓인 간단한 찌개.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "dinner",
            "dietary_tags": ["Spicy", "Vegetarian"],
            "rating": 4.5,
            "cooking_time_minutes": 15,
            "serving_size": 2,
            "instructions": "1. 양파를 칼집낸 뒤 썰어주세요.\n2. 대파도 쫑쫑쫑 썰어줍니다.\n3. 팬에 기름을 넉넉히 두르고 양파, 대파를 볶아줍니다 (약불).\n4. 나머지 양념과 물을 넣어주세요.\n5. 순두부도 넣어줍니다.\n6. 숟가락으로 뚝뚝 대충 잘라주세요.\n7. 보글보글 끓여줍니다.",
            "instructions_en": "1. Slice and cut onion.\n2. Chop green onion.\n3. Heat oil in pan; stir-fry onion and green onion on low heat.\n4. Add remaining seasonings and water.\n5. Add soft tofu; break up with a spoon.\n6. Simmer until boiling.",
            "source": "10000 recipe",
            "image_url": None,
            "ingredients": [
                ("순두부", "1팩", False),
                ("양파", "½개", False),
                ("대파", "한 줌", False),
                ("간장", "2큰술", False),
                ("굴소스", "1큰술", True),
                ("고춧가루", "3큰술", False),
                ("설탕", "⅓큰술", True),
                ("식용유", "약간", False),
            ],
        },
        {
            "id": 30,
            "title": "토마토 스파게티",
            "slug": "tomato-spaghetti",
            "category": "Italian",
            "description": "베이컨, 소시지, 양파와 시판 소스로 만드는 간단한 토마토 스파게티.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "dinner",
            "dietary_tags": [],
            "rating": 4.2,
            "cooking_time_minutes": 25,
            "serving_size": 2,
            "instructions": "1. 끓는 물에 소금 한줌 넣고 스파게티 면을 넣어 7~9분간 삶는다.\n2. 다 삶아지면 물기를 제거한다. (찬물에 헹구지 않는다)\n3. 베이컨을 구워서 잘게 썰어준다.\n4. 양파와 소시지를 적당히 잘라서 같이 볶아준다.\n5. 미리 삶아둔 스파게티 면을 같이 넣고 볶아준다.\n6. 시판 스파게티 소스를 넣고 소스가 적당히 섞이면 완성이다.",
            "instructions_en": "1. Add salt to boiling water; add spaghetti; boil 7-9 minutes stirring to prevent sticking.\n2. Drain. (Do not rinse with cold water.)\n3. Cook bacon; chop into small pieces.\n4. Chop onion and sausage; stir-fry together.\n5. Add cooked spaghetti; stir-fry.\n6. Add 400g spaghetti sauce; stir until combined. Done.",
            "source": "10000 recipe",
            "image_url": None,
            "ingredients": [
                ("스파게티면", "2인분", False),
                ("스파게티 소스", "400g", False),
                ("베이컨", "5장", False),
                ("양파", "½개", False),
                ("소시지", "적당량", True),
            ],
        },
        {
            "id": 31,
            "title": "크림 스파게티",
            "slug": "cream-spaghetti",
            "category": "Italian",
            "description": "생크림과 우유로 만든 소스에 베이컨과 버섯을 넣은 크림 스파게티.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "dinner",
            "dietary_tags": [],
            "rating": 4.5,
            "cooking_time_minutes": 20,
            "serving_size": 1,
            "instructions": "1. 재료들을 모두 잘라 담아주세요.\n2. 면은 끓는 물에 소금 한 꼬집과 기름 한 방울, 7분 정도 삶아주세요.\n3. 삶는 동안에 버터나 올리브유를 팬에 두르고 다진파, 마늘과 볶다가 베이컨, 양파, 버섯을 순서대로 넣어주세요.\n4. 소금과 후추, 간장을 한 스푼 넣고 볶아요.\n5. 볶다가 생크림과 우유를 넣어주세요. 불은 중약불.\n6. 끓으면 슬라이스 치즈도 한 장 넣어주세요.\n7. 건져내어 체에 둔 스파게티 면을 소스에 넣어요.\n8. 마지막으로 끓이면서 후추도 넣고 소금으로 간을 하면 끝!",
            "instructions_en": "1. Cut and prep all ingredients.\n2. Boil noodles in salted water with a drop of oil for 7 minutes.\n3. Heat butter or olive oil in pan; stir-fry green onion and garlic; add bacon, onion, and mushroom in order.\n4. Add salt, pepper, and 1 tbsp soy sauce.\n5. Add heavy cream and milk on medium-low heat.\n6. When boiling, add cheese slice.\n7. Add drained noodles to sauce.\n8. Boil briefly; add pepper; adjust salt. Done.",
            "source": "10000 recipe",
            "image_url": None,
            "ingredients": [
                ("스파게티면", "70g", False),
                ("베이컨", "2줄", False),
                ("양파", "⅛개", False),
                ("표고버섯", "½개", False),
                ("마늘", "1작은술(다진)", False),
                ("생크림", "100ml", False),
                ("우유", "60ml", False),
                ("슬라이스치즈", "1장", False),
                ("간장", "1큰술", False),
                ("대파", "1큰술(다진)", False),
                ("소금", "약간", False),
                ("후춧가루", "약간", False),
                ("올리브유", "약간", False),
            ],
        },
        {
            "id": 32,
            "title": "유부초밥",
            "slug": "yubuchobap",
            "category": "Japanese",
            "description": "피망, 당근, 스팸을 볶아 섞은 밥을 유부에 넣은 유부초밥.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.3,
            "cooking_time_minutes": 25,
            "serving_size": 4,
            "instructions": "1. 당근 ⅓개를 아주 잘게 다져서 준비한다.\n2. 스팸 ½개를 당근처럼 잘게 다져서 준비한다.\n3. 피망은 ½~1개를 잘게 다져서 준비한다.\n4. 후라이팬에 식용유를 2스푼 넣고 피망, 당근, 스팸을 넣고 스팸이 익을 때까지 볶아준다.\n5. 유부를 체에 걸러서 물기를 제거한다.\n6. 갓지은 밥 330g을 준비한다.\n7. 밥에 야채 볶은 것, 초밥 소스, 깨를 넣어 잘 섞는다.\n8. 유부피를 살짝 벌려준 뒤 양념된 밥을 안에 넣으면 완성이다.",
            "instructions_en": "1. Finely mince carrot and Spam.\n2. Finely mince ½ to 1 bell pepper.\n3. Heat 2 tbsp oil; stir-fry bell pepper, carrot, and Spam until Spam is cooked.\n4. Drain inari pouches to remove excess liquid.\n5. Prepare 330g freshly cooked rice.\n6. Mix stir-fried vegetables, kit seasoning sauce, and sesame seeds into rice.\n7. Mix well.\n8. Gently open inari pouch; fill with seasoned rice.",
            "source": "10000 recipe",
            "image_url": None,
            "ingredients": [
                ("유부", "1팩(시판 세트)", False),
                ("밥", "330g", False),
                ("피망", "1개", False),
                ("당근", "⅓개", False),
                ("스팸", "½캔", False),
                ("깨", "1큰술", True),
                ("시판 초밥 소스", "적당량", False),
                ("식용유", "2큰술", False),
            ],
        },
        {
            "id": 33,
            "title": "갈비찜",
            "slug": "galbi-jjim",
            "category": "Korean",
            "description": "소갈비를 간장 양념에 무, 당근, 표고버섯, 밤, 대추와 함께 푹 조린 명절 음식.",
            "cooking_level": "advanced",
            "difficulty": "hard",
            "meal_type": "dinner",
            "dietary_tags": [],
            "rating": 4.9,
            "cooking_time_minutes": 120,
            "serving_size": 4,
            "instructions": "준비하기\n1. 무와 당근은 4cm 폭으로 깍둑 썰어 모서리를 둥글게 다듬는다.\n2. 표고버섯은 물에 불려 기둥을 뗀다.\n3. 밤은 껍질을 벗기고, 대추는 씨를 뺀다.\n4. 간장에 나머지 재료를 섞어서 찜 양념장을 만든다.\n조리하기\n5. 소갈비는 찬물에 담가 핏물을 뺀다. 냄비에 물 5컵을 붓고 끓으면 갈비를 넣어 30분 정도 삶는다. 삶은 갈비를 식혀 질긴 힘줄이나 기름 덩어리를 떼어내고 2cm 간격의 칼집을 사선으로 넣는다.\n6. 소갈비 육수는 차게 식혀 기름을 걷는다.\n7. 다듬은 무와 당근을 끓는 물에 10분 동안 삶아서 건져놓는다.\n8. 냄비에 삶은 갈비를 담고 찜 양념장의 ⅔ 분량을 넣어 버무린 다음 소갈비 육수 2컵을 붓고 중간 불에서 40분 동안 푹 끓인다.\n9. 갈비가 무르게 익으면 삶은 무와 당근, 불린 표고버섯, 밤, 대추를 넣고 남은 양념장을 넣어 약한 불에서 15분 더 끓인다.\n10. 갈비와 채소에 양념 맛이 고르게 들면 그릇에 담는다.",
            "instructions_en": "Preparation:\n1. Cut radish and carrot into 4cm cubes; round off edges.\n2. Rehydrate shiitake; remove stems.\n3. Peel chestnuts; remove jujube seeds.\n4. Mix soy sauce with remaining ingredients for braising sauce.\nCooking:\n5. Soak ribs in cold water to remove blood; boil in 5 cups water 30 minutes; trim tough tendons and fat; make diagonal cuts 2cm apart.\n6. Cool rib broth; skim fat.\n7. Boil radish and carrot in boiling water 10 minutes; drain.\n8. Coat ribs with ⅔ of sauce in pot; add 2 cups rib broth; simmer over medium heat 40 minutes.\n9. Add radish, carrot, shiitake, chestnuts, and jujubes; add remaining sauce; simmer low 15 more minutes.\n10. When well-seasoned, serve.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("소갈비", "1kg", False),
                ("무", "250g", False),
                ("당근", "100g", False),
                ("마른 표고버섯", "6개", False),
                ("밤", "5개", True),
                ("대추", "3개", True),
                ("간장", "4큰술", False),
                ("설탕", "2큰술", False),
                ("배", "4큰술(즙)", True),
                ("대파", "2큰술(다진)", False),
                ("마늘", "1큰술(다진)", False),
                ("참기름", "1큰술", False),
                ("깨소금", "1큰술", True),
            ],
        },
        {
            "id": 34,
            "title": "육개장",
            "slug": "yukgaejang",
            "category": "Korean",
            "description": "소고기와 대파를 고추기름 양념에 끓인 얼큰한 국.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "dinner",
            "dietary_tags": ["Spicy"],
            "rating": 4.7,
            "cooking_time_minutes": 60,
            "serving_size": 4,
            "instructions": "준비하기\n1. 소고기는 4등분하여 찬물에 30분 동안 담가 핏물을 뺀다.\n2. 냄비에 물 12컵을 부어 팔팔 끓으면 소고기와 대파 1대, 마늘 6쪽을 넣고 중간 불에서 30분 정도 끓이면서 위에 뜨는 기름과 거품을 걷어낸다.\n3. 삶은 고기는 건져서 잘게 찢거나 얇게 저며 썰고, 육수는 식혀서 체에 면포를 깔고 거른다.\n4. 나머지 대파는 반으로 갈라 6cm 길이로 토막 내어 끓는 물에 살짝 데친다.\n5. 그릇에 고춧가루를 담고 식용유를 조금씩 넣으면서 잘 섞어 고추기름을 만든 다음 다진 파, 다진 마늘, 국간장, 참기름, 후춧가루를 섞어 양념을 만든다.\n조리하기\n1. 삶은 고기를 양념에 무친다.\n2. 육수를 냄비에 담고 양념한 고기를 넣어 끓인다. 끓어오르면 데친 파를 넣고 5분 더 끓인 뒤 국간장으로 간을 맞추어 5분간 더 끓여낸다.",
            "instructions_en": "Preparation:\n1. Quarter brisket; soak in cold water 30 minutes.\n2. Boil 12 cups water; add beef, 1 green onion, and 6 garlic. Simmer 30 minutes; skim fat and foam.\n3. Shred cooked beef; strain and cool broth.\n4. Halve remaining green onion; cut 6cm; blanch briefly.\n5. Mix chili powder with oil to make chili oil; add remaining seasoning ingredients.\nCooking:\n1. Coat shredded beef with seasoning.\n2. Bring broth to boil; add seasoned beef. When boiling, add blanched green onion; cook 5 more minutes; season with soup soy sauce; cook 5 more minutes.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("소고기(양지머리)", "500g", False),
                ("대파", "6대", False),
                ("마늘", "6쪽", False),
                ("고춧가루", "3큰술", False),
                ("식용유", "3큰술", False),
                ("국간장", "2큰술", False),
                ("참기름", "2큰술", False),
                ("후춧가루", "¼작은술", False),
            ],
        },
        {
            "id": 35,
            "title": "감자탕",
            "slug": "gamja-tang",
            "category": "Korean",
            "description": "돼지 등뼈와 감자, 시래기를 넣어 끓인 진한 국물 요리.",
            "cooking_level": "advanced",
            "difficulty": "hard",
            "meal_type": "dinner",
            "dietary_tags": ["Spicy"],
            "rating": 4.7,
            "cooking_time_minutes": 90,
            "serving_size": 4,
            "instructions": "준비하기\n1. 돼지 등뼈는 찬물에 3시간 동안 담가서 핏물을 뺀다.\n2. 감자는 껍질을 벗겨 반으로 가르고, 양파와 깻잎은 4등분한다.\n3. 풋고추는 어슷하게 썰어 씨를 빼고, 대파도 어슷하게 썬다.\n4. 고춧가루에 나머지 재료를 섞어서 양념장을 만든다.\n조리하기\n1. 돼지 등뼈는 끓는 물에 10분 동안 삶아 건져서 찬물에 씻은 뒤 다시 돼지 등뼈가 잠길 정도로 찬물을 붓고 대파, 마늘, 생강, 청주와 감자를 넣어 약한 불에서 40분 동안 푹 끓인다.\n2. 시래기를 넣고 20분 동안 푹 끓인다.\n3. 소금으로 간을 맞춘 뒤 양파, 깻잎, 풋고추, 대파를 넣고 5분 정도 더 끓인다.\n4. 마지막으로 들깨 가루를 섞고 불을 끈 뒤 그릇에 담아낸다.",
            "instructions_en": "Preparation:\n1. Soak pork spine in cold water 3 hours.\n2. Peel and halve potatoes; quarter onions and perilla.\n3. Slice chilies diagonally; slice green onion diagonally.\n4. Make seasoning sauce.\nCooking:\n1. Boil pork spine 10 minutes; rinse; add cold water with green onion, garlic, ginger, cheongju, and potatoes; simmer on low 40 minutes.\n2. Add dried radish greens; simmer 20 minutes.\n3. Season with salt; add onions, perilla, chilies, and green onion; cook 5 more minutes.\n4. Stir in perilla seed powder; turn off heat; serve.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("돼지 등뼈", "1kg", False),
                ("감자", "5개", False),
                ("양파", "2개", False),
                ("시래기", "300g(삶은)", False),
                ("깻잎", "10장", True),
                ("풋고추", "3개", True),
                ("대파", "4대", False),
                ("마늘", "12쪽", False),
                ("생강", "30g", False),
                ("청주", "2큰술", False),
                ("고춧가루", "3큰술", False),
                ("고추장", "1큰술", False),
                ("국간장", "4큰술", False),
                ("참기름", "1큰술", False),
                ("들깨 가루", "2큰술", True),
                ("들기름", "약간", True),
            ],
        },
        {
            "id": 36,
            "title": "갈비탕",
            "slug": "galbi-tang",
            "category": "Korean",
            "description": "소갈비를 무와 함께 맑게 끓인 깊은 맛의 탕.",
            "cooking_level": "advanced",
            "difficulty": "hard",
            "meal_type": "dinner",
            "dietary_tags": [],
            "rating": 4.8,
            "cooking_time_minutes": 120,
            "serving_size": 4,
            "instructions": "준비하기\n1. 소갈비는 찬물에 담가 핏물을 뺀다.\n2. 무는 4cm 크기로 토막 썬다.\n3. 계란은 깨뜨려서 흰자와 노른자로 나누어 소금을 넣고 풀어놓는다. 약한 불에서 얇게 황백 지단으로 부쳐 5cm 길이로 가늘게 채 썬다.\n4. 대파는 어슷하게 썬다.\n5. 국간장에 나머지 재료를 섞어서 삶은 갈비 양념장을 만든다.\n조리하기\n1. 냄비에 물 12컵을 붓고 소갈비, 대파, 통마늘을 넣어 중간 불에서 30분 정도 끓이며 거품과 기름을 걷어낸다.\n2. 무는 끓는 물에 넣고 중간 불에서 30분 동안 삶아 건진다.\n3. 갈비가 무르게 익으면 식혀서 질긴 힘줄이나 기름 덩어리를 떼어낸 뒤 1cm 간격으로 칼집을 어슷하게 넣어서 삶은 갈비 양념장에 버무린다.\n4. 무는 4×2.5×2.5cm 크기로 썬다.\n5. 기름을 걷어낸 국물에 양념한 갈비와 무를 넣고 약한 불에서 30분 동안 끓인 뒤 국간장, 다진 마늘, 어슷 썬 대파를 넣고 5분 동안 더 끓여서 소금으로 간을 맞춘다.\n6. 그릇에 갈비탕을 담고 채 썬 지단을 얹어서 낸다.",
            "instructions_en": "Preparation:\n1. Soak ribs in cold water to remove blood.\n2. Cut radish into 4cm chunks.\n3. Separate egg; add salt to each part; fry into thin jidan; cut into fine 5cm strips.\n4. Slice green onion diagonally.\n5. Mix soup soy sauce with remaining ingredients for rib seasoning.\nCooking:\n1. Boil ribs in 12 cups water with green onion and garlic over medium heat 30 minutes; skim foam and fat.\n2. Boil radish in boiling water 30 minutes; drain.\n3. When ribs are tender, cool; trim tendons and fat; cut diagonal slits 1cm apart; coat with seasoning.\n4. Cut radish into 4×2.5×2.5cm pieces.\n5. Add ribs and radish to skimmed broth; simmer low 30 minutes; add soup soy sauce, garlic, and sliced green onion; cook 5 more minutes; season with salt.\n6. Serve topped with jidan strips.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("소갈비", "1kg", False),
                ("무", "300g", False),
                ("대파", "2대", False),
                ("마늘", "6쪽", False),
                ("계란", "1개", True),
                ("국간장", "4큰술", False),
                ("소금", "약간", False),
            ],
        },
        {
            "id": 37,
            "title": "미역국",
            "slug": "miyeok-guk",
            "category": "Korean",
            "description": "소고기와 미역을 참기름에 볶아 끓인 구수한 미역국.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "dinner",
            "dietary_tags": [],
            "rating": 4.6,
            "cooking_time_minutes": 35,
            "serving_size": 4,
            "instructions": "준비하기\n1. 소고기는 납작납작하게 썰어서 국간장과 다진 마늘을 넣고 무친다.\n2. 마른 미역은 물을 넉넉하게 부어 20분 정도 불린다. 먹기 좋은 크기로 작게 썰어 물기를 꼭 짠다.\n조리하기\n1. 달군 냄비에 참기름을 두르고 양념한 고기가 반 정도 익을 때까지 볶는다.\n2. 냄비에 미역을 넣고 볶다가 물 8컵을 부어 센 불에서 끓인다.\n3. 물이 끓으면 불을 약하게 줄이고 국간장과 소금으로 간을 맞춘다. 20분간 더 끓인 뒤 후춧가루를 약간 넣는다.",
            "instructions_en": "Preparation:\n1. Slice beef thinly; season with soup soy sauce and garlic.\n2. Soak dried seaweed in plenty of water for 20 minutes; cut into bite-sized pieces; squeeze out moisture.\nCooking:\n1. Heat sesame oil in pot; stir-fry seasoned beef until half-cooked.\n2. Add seaweed; stir-fry; add 8 cups water; bring to boil over high heat.\n3. Reduce to low heat; season with soup soy sauce and salt. Simmer 20 more minutes; add a pinch of pepper.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("소고기(양지머리)", "200g", False),
                ("마른 미역", "30g", False),
                ("국간장", "1큰술", False),
                ("마늘", "1작은술(다진)", False),
                ("참기름", "2큰술", False),
                ("소금", "약간", False),
                ("후춧가루", "약간", True),
            ],
        },
        {
            "id": 38,
            "title": "콩나물국",
            "slug": "kongnamul-guk",
            "category": "Korean",
            "description": "콩나물을 참기름에 볶아 끓인 시원한 국.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "dinner",
            "dietary_tags": ["Vegan"],
            "rating": 4.4,
            "cooking_time_minutes": 30,
            "serving_size": 4,
            "instructions": "준비하기\n1. 콩나물은 뿌리를 떼고 씻어서 물기를 뺀다.\n2. 대파는 어슷하게 썬다.\n조리하기\n1. 뜨겁게 달군 냄비에 참기름을 두른 뒤 콩나물을 넣고 소금을 뿌린 다음, 물 ½컵을 넣고 뚜껑을 덮어 약한 불에서 10분 동안 끓인다. 남은 물을 더 붓고 중간 불에서 15분 동안 끓인다.\n2. 콩나물국이 끓으면 어슷 썬 파와 다진 마늘을 넣고 국간장과 소금으로 간을 맞추어 3분 정도 더 끓인다.",
            "instructions_en": "Preparation:\n1. Trim bean sprout roots; wash and drain.\n2. Slice green onion diagonally.\nCooking:\n1. Heat pot with sesame oil; add bean sprouts, sprinkle salt, add ½ cup water; cover; simmer low 10 minutes. Add remaining water; cook medium 15 minutes.\n2. When boiling, add green onion and garlic; season with soup soy sauce and salt; cook 3 more minutes.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("콩나물", "500g", False),
                ("참기름", "1큰술", False),
                ("대파", "½대", False),
                ("마늘", "1작은술(다진)", False),
                ("국간장", "2큰술", False),
                ("소금", "약간", False),
            ],
        },
        {
            "id": 39,
            "title": "잔치국수",
            "slug": "janchi-guksu",
            "category": "Korean",
            "description": "멸치장국에 애호박, 당근, 계란 지단을 얹어 먹는 잔치국수.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "lunch",
            "dietary_tags": [],
            "rating": 4.5,
            "cooking_time_minutes": 40,
            "serving_size": 4,
            "instructions": "준비하기\n1. 국물용 멸치의 머리와 내장을 떼어내 냄비에 넣고 물 10컵을 부어 센 불에서 끓인다. 끓어오르면 중간 불에서 20분 정도 더 끓인 뒤 면포를 얹은 체에 걸러 청주, 국간장, 소금을 넣고 간을 맞춘다.\n2. 애호박은 5cm 길이로 토막 내어 가늘게 채 썬 다음 소금 ⅓작은술을 뿌려 30분간 절인다. 물기를 꼭 짜고 팬에 살짝 볶는다.\n3. 당근도 5cm 길이로 토막 내어 곱게 채 썰어 센 불에서 1분 정도 볶은 후 소금으로 간한다.\n4. 계란은 깨뜨려서 황백 지단으로 부쳐 5cm 길이로 가늘게 채 썬다.\n조리하기\n1. 큰 냄비에 물을 끓여 국수를 넣어 3~4분간 삶아서 찬물에 여러 번 헹구어 물기를 뺀다.\n2. 각자의 그릇에 삶은 국수를 담고 준비한 애호박, 당근, 지단을 얹고 간을 맞춘 뜨거운 멸치장국을 조심스럽게 부어 상에 바로 낸다.",
            "instructions_en": "Preparation:\n1. Remove anchovy heads and entrails; boil in 10 cups water; reduce 20 minutes; strain; season.\n2. Cut zucchini into 5cm strips; sprinkle salt; pickle 30 minutes; squeeze dry; stir-fry briefly.\n3. Julienne carrot; stir-fry 1 minute over high heat; season with salt.\n4. Separate eggs; add salt to each; fry into thin jidan; julienne 5cm strips.\nCooking:\n1. Boil noodles in boiling water; rinse cold; drain.\n2. Serve noodles in individual bowls; top with zucchini, carrot, and jidan; pour hot broth carefully; serve immediately.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("소면", "500g", False),
                ("애호박", "½개", False),
                ("당근", "⅙개", False),
                ("계란", "2개", True),
                ("국물용 멸치", "20마리", False),
                ("청주", "1큰술", False),
                ("국간장", "2큰술", False),
                ("소금", "1큰술", False),
            ],
        },
        {
            "id": 40,
            "title": "비빔국수",
            "slug": "bibim-guksu",
            "category": "Korean",
            "description": "초고추장 양념에 김치, 오이, 상추, 양파를 얹어 비벼 먹는 소면.",
            "cooking_level": "beginner",
            "difficulty": "easy",
            "meal_type": "lunch",
            "dietary_tags": ["Spicy"],
            "rating": 4.6,
            "cooking_time_minutes": 20,
            "serving_size": 4,
            "instructions": "준비하기\n1. 김치는 소를 털고 송송 썬 다음 꼭 짜서 참기름과 설탕을 넣고 무친다.\n2. 오이는 어슷하게 썰어서 가늘게 채 썬다.\n3. 상추는 깨끗이 씻어 물기를 빼고 1cm 두께로 굵게 채 썬다.\n4. 양파는 반으로 가르고 길이대로 곱게 채 썰어 찬물에 10분쯤 담갔다가 물기를 걷는다.\n5. 고춧가루에 나머지 재료를 섞어서 비빔 양념장을 만든다.\n조리하기\n1. 큰 냄비에 물을 끓여 국수를 넣어 3~4분간 삶아서 찬물에 여러 번 헹구어 물기를 뺀다.\n2. 큰 그릇에 삶은 국수를 모두 담은 뒤 비빔 양념장을 넣고 비벼서 1인분씩 나누어 담는다.\n3. 준비된 김치, 오이, 상추, 양파, 삶은 계란 반 개를 올리고 구운 김을 부수어 고루 뿌린 뒤 비벼 먹는다.",
            "instructions_en": "Preparation:\n1. Chop kimchi; squeeze dry; mix with sesame oil and sugar.\n2. Slice cucumber diagonally; julienne finely.\n3. Wash lettuce; drain; cut 1cm wide.\n4. Julienne onion; soak in cold water 10 minutes; drain.\n5. Mix chili powder with remaining ingredients for spicy sauce.\nCooking:\n1. Boil noodles in boiling water; rinse cold multiple times; drain.\n2. Mix all cooked noodles with spicy sauce; divide into portions.\n3. Top with kimchi, cucumber, lettuce, onion, ½ boiled egg, and crumbled seaweed; toss before eating.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("소면", "500g", False),
                ("배추김치", "500g", False),
                ("오이", "½개", False),
                ("상추", "4장", False),
                ("양파", "½개", False),
                ("계란", "2개(삶은)", True),
                ("구운 김", "2장", True),
                ("고춧가루", "1큰술", False),
                ("고추장", "4큰술", False),
                ("간장", "2큰술", False),
                ("설탕", "2큰술", False),
                ("물엿", "2큰술", False),
                ("식초", "4큰술", False),
                ("참기름", "1큰술", False),
                ("깨소금", "1큰술", True),
            ],
        },
        {
            "id": 41,
            "title": "오징어 덮밥",
            "slug": "ojingeo-deopbap",
            "category": "Korean",
            "description": "매콤한 양념에 볶은 오징어를 밥 위에 올린 덮밥.",
            "cooking_level": "intermediate",
            "difficulty": "medium",
            "meal_type": "dinner",
            "dietary_tags": ["Spicy"],
            "rating": 4.6,
            "cooking_time_minutes": 30,
            "serving_size": 4,
            "instructions": "준비하기\n1. 오징어는 먹물주머니를 꺼내고 다리를 분리한다. 몸통은 길이대로 반 갈라 껍질을 벗긴다.\n2. 손질한 오징어는 안쪽에 0.6cm 간격으로 어슷하게 칼집을 넣어 5×3cm 크기로 썬다. 다리도 5cm 길이로 썬다.\n3. 양파는 반 갈라서 길이로 채 썬다.\n4. 당근은 4×1×0.3cm 크기로 납작하게 채 썬다.\n5. 풋고추, 홍고추는 반 갈라서 씨를 빼고 어슷하게 썬다.\n6. 대파는 어슷하게 썰고, 깻잎은 1cm 폭으로 썬다.\n7. 고추장에 나머지 재료를 섞어서 볶음 양념장을 만든다.\n조리하기\n1. 손질한 오징어를 볶음 양념장에 버무린 다음 준비한 채소를 모두 넣고 섞는다.\n2. 뜨겁게 달군 팬에 식용유를 두르고 양념한 오징어와 채소를 넣어 센 불에서 오징어가 불투명해지고 칼집 낸 곳이 솔 모양이 될 때까지 5분간 볶는다. 마지막으로 녹말물을 넣어 섞은 다음 불을 끄고 밥 위에 담아낸다.",
            "instructions_en": "Preparation:\n1. Remove ink sac and peel squid skin.\n2. Score inside of body diagonally; cut into 5×3cm pieces. Cut legs into 5cm lengths.\n3. Julienne onion lengthwise.\n4. Julienne carrot 4×1×0.3cm.\n5. Halve chilies; remove seeds; slice diagonally.\n6. Slice green onion diagonally; cut perilla into 1cm strips.\n7. Mix gochujang with remaining ingredients for stir-fry sauce.\nCooking:\n1. Coat squid with sauce; add all vegetables; mix.\n2. Stir-fry in oiled pan over high heat for 5 minutes until squid turns opaque. Add starch water; mix; serve over rice.",
            "source": "한식진흥원",
            "image_url": None,
            "ingredients": [
                ("밥", "4공기", False),
                ("오징어", "2마리", False),
                ("양파", "½개", False),
                ("풋고추", "2개", True),
                ("홍고추", "1개", True),
                ("깻잎", "4장", True),
                ("당근", "30g", False),
                ("대파", "1대", False),
                ("고추장", "2큰술", False),
                ("고춧가루", "1큰술", False),
                ("간장", "1큰술", False),
                ("설탕", "1큰술", False),
                ("물엿", "1큰술", False),
                ("마늘", "1큰술(다진)", False),
                ("생강", "1작은술(다진)", True),
                ("청주", "1큰술", False),
                ("참기름", "½큰술", False),
                ("녹말가루", "1큰술", False),
                ("식용유", "1큰술", False),
            ],
        },
    ]

    for row in recipe_rows:
        recipe = Recipe(
            id=row["id"],
            title=row["title"],
            slug=row["slug"],
            category=row["category"],
            description=row["description"],
            cooking_level=row["cooking_level"],
            difficulty=row["difficulty"],
            meal_type=row["meal_type"],
            dietary_tags=row["dietary_tags"],
            rating=row["rating"],
            cooking_time_minutes=row["cooking_time_minutes"],
            serving_size=row["serving_size"],
            instructions=row["instructions"],
            instructions_en=row["instructions_en"],
            source=row["source"],
            image_url=row["image_url"],
        )
        db.add(recipe)
        db.flush()
        for ingredient_name, amount, is_optional in row["ingredients"]:
            db.add(
                RecipeIngredient(
                    recipe_id=recipe.id,
                    ingredient_id=ingredients[ingredient_name].id,
                    amount=amount,
                    is_optional=is_optional,
                )
            )

    db.add(SavedRecipe(user_id=SAMPLE_USER_ID, recipe_id=2))
    db.add(SavedRecipe(user_id=SAMPLE_USER_ID, recipe_id=3))
    db.add(SavedRecipe(user_id=SAMPLE_USER_ID, recipe_id=21))
    db.add(SavedRecipe(user_id=SAMPLE_USER_ID, recipe_id=24))
    db.add(SavedRecipe(user_id=SAMPLE_USER_ID, recipe_id=37))

    db.commit()
